<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-EUU5Q1J4" name="tll.parentportal.scripts.ParentLogin" tests="3" failures="0" timestamp="10 Feb 2021 11:41:23 GMT" time="1.934" errors="1">
  <testcase name="TC003_Plandingpage" time="0.014" classname="tll.parentportal.scripts.ParentLogin">
    <error type="java.lang.AssertionError" message="expected [http://104.215.189.175:1019/AdminLogin] but found [http://104.215.189.175:1019/adminlogin]">
      <![CDATA[java.lang.AssertionError: expected [http://104.215.189.175:1019/AdminLogin] but found [http://104.215.189.175:1019/adminlogin]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at tll.generic.SeleniumLibrary.validate(SeleniumLibrary.java:37)
	at tll.parentportal.scripts.ParentLogin.TC003_Plandingpage(ParentLogin.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:343)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:305)
	at org.testng.SuiteRunner.run(SuiteRunner.java:254)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC003_Plandingpage -->
  <testcase name="TC001_plogintitle" time="0.036" classname="tll.parentportal.scripts.ParentLogin"/>
  <testcase name="TC002_Ploginpage" time="1.884" classname="tll.parentportal.scripts.ParentLogin"/>
</testsuite> <!-- tll.parentportal.scripts.ParentLogin -->
